apiVersion: v1
kind: Pod
metadata:
    name: nginx
spec:
   containers:
   - image: nginx:alpine
     name: nginx-container
     volumeMounts:
     - mountPath: /var/www/html
       name: local-pvc-volume
   volumes:
   - name: local-pvc-volume
     persistentVolumeClaim:
         claimName: local-pvc